# Generated by Django 5.1.1 on 2024-10-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="slug",
            field=models.SlugField(editable=False, max_length=300, unique=True),
        ),
    ]
